### ISSUE TITLE
nlp dataset

### ISSUE THREAD

**Issue by p-null** [maximedb/nlp_papers#2]
Hey, Maxime!
I am glad to find someone who is into using NLP techniques to predict stock market trend.
I am also working on a research project which use textual data to predict stock market trend.
Many of my methods are adapted from SoAT from latest papers. What I am lack of is quality financial dataset. The dataset I am currently using is tweets which has so much noise.
Can you kindly share some quality dataset that can be used to predict the stock market trend?
Do you want to have a quick chat on this topic? I have sent you an email!

**Comment by maximedb** [comment]
Hi Tingkai,
You can find some earnings calls transcripts here: https://maximedb.be
